//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenMon
    {
        public ChuyenMon()
        {
            this.LopHoc = new HashSet<LopHoc>();
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public int MaCM { get; set; }
        public string TenChuyenMon { get; set; }
    
        public virtual ICollection<LopHoc> LopHoc { get; set; }
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
