//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyGoiTap
    {
        public int MaDKGT { get; set; }
        public int MaKH { get; set; }
        public int MaGoiTap { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string TrangThai { get; set; }
    
        public virtual GoiTap GoiTap { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
