//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.CheckIn = new HashSet<CheckIn>();
            this.DangKyGoiTap = new HashSet<DangKyGoiTap>();
            this.DangKyLop = new HashSet<DangKyLop>();
            this.DangKyPT = new HashSet<DangKyPT>();
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<int> MaLoaiKH { get; set; }
        public string GioiTinh { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    
        public virtual ICollection<CheckIn> CheckIn { get; set; }
        public virtual ICollection<DangKyGoiTap> DangKyGoiTap { get; set; }
        public virtual ICollection<DangKyLop> DangKyLop { get; set; }
        public virtual ICollection<DangKyPT> DangKyPT { get; set; }
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
    }
}
