//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        public LopHoc()
        {
            this.DangKyLop = new HashSet<DangKyLop>();
            this.LichLop = new HashSet<LichLop>();
        }
    
        public int MaLop { get; set; }
        public string TenLop { get; set; }
        public int MaCM { get; set; }
        public decimal HocPhi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int SoBuoi { get; set; }
        public Nullable<int> SiSoToiDa { get; set; }
    
        public virtual ChuyenMon ChuyenMon { get; set; }
        public virtual ICollection<DangKyLop> DangKyLop { get; set; }
        public virtual ICollection<LichLop> LichLop { get; set; }
    }
}
