//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.DangKyPT = new HashSet<DangKyPT>();
            this.LichLop = new HashSet<LichLop>();
            this.ChuyenMon = new HashSet<ChuyenMon>();
        }
    
        public int MaNV { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string GioiTinh { get; set; }
        public string TenNV { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual ICollection<DangKyPT> DangKyPT { get; set; }
        public virtual ICollection<LichLop> LichLop { get; set; }
        public virtual ICollection<ChuyenMon> ChuyenMon { get; set; }
    }
}
