//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QL_PHONGGYMEntities2 : DbContext
    {
        public QL_PHONGGYMEntities2()
            : base("name=QL_PHONGGYMEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CheckIn> CheckIn { get; set; }
        public DbSet<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public DbSet<ChucVu> ChucVu { get; set; }
        public DbSet<ChuyenMon> ChuyenMon { get; set; }
        public DbSet<DangKyGoiTap> DangKyGoiTap { get; set; }
        public DbSet<DangKyLop> DangKyLop { get; set; }
        public DbSet<DangKyPT> DangKyPT { get; set; }
        public DbSet<GoiTap> GoiTap { get; set; }
        public DbSet<HoaDon> HoaDon { get; set; }
        public DbSet<KhachHang> KhachHang { get; set; }
        public DbSet<LichLop> LichLop { get; set; }
        public DbSet<LichTapPT> LichTapPT { get; set; }
        public DbSet<LoaiKhachHang> LoaiKhachHang { get; set; }
        public DbSet<LoaiSanPham> LoaiSanPham { get; set; }
        public DbSet<LopHoc> LopHoc { get; set; }
        public DbSet<NhanVien> NhanVien { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        [EdmFunction("QL_PHONGGYMEntities2", "f_GetKhachHangHetHanTrongTuan")]
        public virtual IQueryable<f_GetKhachHangHetHanTrongTuan_Result> f_GetKhachHangHetHanTrongTuan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_GetKhachHangHetHanTrongTuan_Result>("[QL_PHONGGYMEntities2].[f_GetKhachHangHetHanTrongTuan]()");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_BaoCaoDoanhThu(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_BaoCaoDoanhThu", tuNgayParameter, denNgayParameter);
        }
    
        public virtual int sp_CapNhatLoaiKhachHang(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatLoaiKhachHang", maKHParameter);
        }
    
        public virtual ObjectResult<string> sp_CheckInKhachHang(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_CheckInKhachHang", maKHParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_DangKyGoiTap(Nullable<int> maKH, Nullable<int> maGoiTap, Nullable<System.DateTime> ngayBatDau)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maGoiTapParameter = maGoiTap.HasValue ?
                new ObjectParameter("MaGoiTap", maGoiTap) :
                new ObjectParameter("MaGoiTap", typeof(int));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyGoiTap", maKHParameter, maGoiTapParameter, ngayBatDauParameter);
        }
    
        public virtual int sp_DangKyLop(Nullable<int> maKH, Nullable<int> maLop)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyLop", maKHParameter, maLopParameter);
        }
    
        public virtual int sp_DangKyPT(Nullable<int> maKH, Nullable<int> maNV, Nullable<int> soBuoi, Nullable<decimal> giaMoiBuoi)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var soBuoiParameter = soBuoi.HasValue ?
                new ObjectParameter("SoBuoi", soBuoi) :
                new ObjectParameter("SoBuoi", typeof(int));
    
            var giaMoiBuoiParameter = giaMoiBuoi.HasValue ?
                new ObjectParameter("GiaMoiBuoi", giaMoiBuoi) :
                new ObjectParameter("GiaMoiBuoi", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyPT", maKHParameter, maNVParameter, soBuoiParameter, giaMoiBuoiParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_GanChuyenMonChoNhanVien(Nullable<int> maNV, Nullable<int> maCM)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GanChuyenMonChoNhanVien", maNVParameter, maCMParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_KhachHangDangKy(string tenKH, string gioiTinh, Nullable<System.DateTime> ngaySinh, string sDT, string email, string tenDangNhap, string matKhau)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhachHangDangKy", tenKHParameter, gioiTinhParameter, ngaySinhParameter, sDTParameter, emailParameter, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_KhachHangLogin(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_KhachHangLogin", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<KhachHang> sp_KhachHangLogin(string tenDangNhap, string matKhau, MergeOption mergeOption)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("sp_KhachHangLogin", mergeOption, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_LapHoaDon(Nullable<int> maKH, Nullable<decimal> giamGia)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var giamGiaParameter = giamGia.HasValue ?
                new ObjectParameter("GiamGia", giamGia) :
                new ObjectParameter("GiamGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LapHoaDon", maKHParameter, giamGiaParameter);
        }
    
        public virtual ObjectResult<sp_NhanVienLogin_Result> sp_NhanVienLogin(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NhanVienLogin_Result>("sp_NhanVienLogin", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_ThanhToanHoaDon(Nullable<int> maHD)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanHoaDon", maHDParameter);
        }
    
        public virtual int sp_ThemChucVu(string tenChucVu)
        {
            var tenChucVuParameter = tenChucVu != null ?
                new ObjectParameter("TenChucVu", tenChucVu) :
                new ObjectParameter("TenChucVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChucVu", tenChucVuParameter);
        }
    
        public virtual int sp_ThemChuyenMon(string tenChuyenMon)
        {
            var tenChuyenMonParameter = tenChuyenMon != null ?
                new ObjectParameter("TenChuyenMon", tenChuyenMon) :
                new ObjectParameter("TenChuyenMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChuyenMon", tenChuyenMonParameter);
        }
    
        public virtual int sp_ThemGoiTap(string tenGoi, Nullable<int> thoiHan, Nullable<decimal> gia)
        {
            var tenGoiParameter = tenGoi != null ?
                new ObjectParameter("TenGoi", tenGoi) :
                new ObjectParameter("TenGoi", typeof(string));
    
            var thoiHanParameter = thoiHan.HasValue ?
                new ObjectParameter("ThoiHan", thoiHan) :
                new ObjectParameter("ThoiHan", typeof(int));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemGoiTap", tenGoiParameter, thoiHanParameter, giaParameter);
        }
    
        public virtual int sp_ThemKhachHang(string tenKH, string gioiTinh, Nullable<System.DateTime> ngaySinh, string sDT, string email, Nullable<int> maLoaiKH)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var maLoaiKHParameter = maLoaiKH.HasValue ?
                new ObjectParameter("MaLoaiKH", maLoaiKH) :
                new ObjectParameter("MaLoaiKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhachHang", tenKHParameter, gioiTinhParameter, ngaySinhParameter, sDTParameter, emailParameter, maLoaiKHParameter);
        }
    
        public virtual int sp_ThemLichLop(Nullable<int> maLop, Nullable<int> maNV, Nullable<System.DateTime> ngayHoc, Nullable<System.TimeSpan> gioBatDau, Nullable<System.TimeSpan> gioKetThuc)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var ngayHocParameter = ngayHoc.HasValue ?
                new ObjectParameter("NgayHoc", ngayHoc) :
                new ObjectParameter("NgayHoc", typeof(System.DateTime));
    
            var gioBatDauParameter = gioBatDau.HasValue ?
                new ObjectParameter("GioBatDau", gioBatDau) :
                new ObjectParameter("GioBatDau", typeof(System.TimeSpan));
    
            var gioKetThucParameter = gioKetThuc.HasValue ?
                new ObjectParameter("GioKetThuc", gioKetThuc) :
                new ObjectParameter("GioKetThuc", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLichLop", maLopParameter, maNVParameter, ngayHocParameter, gioBatDauParameter, gioKetThucParameter);
        }
    
        public virtual int sp_ThemLichTapPT(Nullable<int> maDKPT, Nullable<System.DateTime> ngayTap, Nullable<System.TimeSpan> gioBatDau, Nullable<System.TimeSpan> gioKetThuc)
        {
            var maDKPTParameter = maDKPT.HasValue ?
                new ObjectParameter("MaDKPT", maDKPT) :
                new ObjectParameter("MaDKPT", typeof(int));
    
            var ngayTapParameter = ngayTap.HasValue ?
                new ObjectParameter("NgayTap", ngayTap) :
                new ObjectParameter("NgayTap", typeof(System.DateTime));
    
            var gioBatDauParameter = gioBatDau.HasValue ?
                new ObjectParameter("GioBatDau", gioBatDau) :
                new ObjectParameter("GioBatDau", typeof(System.TimeSpan));
    
            var gioKetThucParameter = gioKetThuc.HasValue ?
                new ObjectParameter("GioKetThuc", gioKetThuc) :
                new ObjectParameter("GioKetThuc", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLichTapPT", maDKPTParameter, ngayTapParameter, gioBatDauParameter, gioKetThucParameter);
        }
    
        public virtual int sp_ThemLoaiKhachHang(string tenLoai, Nullable<decimal> mucGiam)
        {
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            var mucGiamParameter = mucGiam.HasValue ?
                new ObjectParameter("MucGiam", mucGiam) :
                new ObjectParameter("MucGiam", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLoaiKhachHang", tenLoaiParameter, mucGiamParameter);
        }
    
        public virtual int sp_ThemLoaiSanPham(string tenLoaiSP)
        {
            var tenLoaiSPParameter = tenLoaiSP != null ?
                new ObjectParameter("TenLoaiSP", tenLoaiSP) :
                new ObjectParameter("TenLoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLoaiSanPham", tenLoaiSPParameter);
        }
    
        public virtual int sp_ThemLopHoc(string tenLop, Nullable<int> maCM, Nullable<decimal> hocPhi, Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, Nullable<int> soBuoi, Nullable<int> siSoToiDa)
        {
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            var hocPhiParameter = hocPhi.HasValue ?
                new ObjectParameter("HocPhi", hocPhi) :
                new ObjectParameter("HocPhi", typeof(decimal));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            var soBuoiParameter = soBuoi.HasValue ?
                new ObjectParameter("SoBuoi", soBuoi) :
                new ObjectParameter("SoBuoi", typeof(int));
    
            var siSoToiDaParameter = siSoToiDa.HasValue ?
                new ObjectParameter("SiSoToiDa", siSoToiDa) :
                new ObjectParameter("SiSoToiDa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLopHoc", tenLopParameter, maCMParameter, hocPhiParameter, ngayBatDauParameter, ngayKetThucParameter, soBuoiParameter, siSoToiDaParameter);
        }
    
        public virtual int sp_ThemNhanVien(Nullable<int> maChucVu, string tenDangNhap, string matKhau, string gioiTinh, string tenNV, string sDT, Nullable<System.DateTime> ngaySinh)
        {
            var maChucVuParameter = maChucVu.HasValue ?
                new ObjectParameter("MaChucVu", maChucVu) :
                new ObjectParameter("MaChucVu", typeof(int));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", maChucVuParameter, tenDangNhapParameter, matKhauParameter, gioiTinhParameter, tenNVParameter, sDTParameter, ngaySinhParameter);
        }
    
        public virtual int sp_ThemSanPham(string tenSP, Nullable<int> maLoaiSP, Nullable<decimal> donGia, Nullable<int> soLuongTon)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", tenSPParameter, maLoaiSPParameter, donGiaParameter, soLuongTonParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
